#ifndef LIB_RENDERER_SRC_RENDERER_LIB_HANDMADEMATH_IMPL
#define LIB_RENDERER_SRC_RENDERER_LIB_HANDMADEMATH_IMPL

#define HANDMADE_MATH_IMPLEMENTATION
#include "HandmadeMath.h"

#endif /* LIB_RENDERER_SRC_RENDERER_LIB_HANDMADEMATH_IMPL */
