#ifndef LIB_RENDERER_SRC_RENDERER_LIB_SOKOL_GFX_IMPL
#define LIB_RENDERER_SRC_RENDERER_LIB_SOKOL_GFX_IMPL

#define SOKOL_IMPL
#define SOKOL_GLCORE33
#include "sokol_gfx.h"

#endif /* LIB_RENDERER_SRC_RENDERER_LIB_SOKOL_GFX_IMPL */
