export const EVENTS = {
    CREATE_OBJECT: 0x02,
    CREATE_PERMANENT_OBJECT: 0x02,
    DELETE_OBJECT: 0x04,
    UPDATE_OBJECT: 0x08,
    HIDE_OBJECT: 0x0C,

    GAMES_LIST_QUERY: 0x81,
    TOP_LIST_QUERY: 0x82,
    ATTACH_TO_GAME: 0x83,
    RESTORE_CONNECTION: 0x84,
    CLOSE_SOCKET: 0x86,
    REGISTER_NAME: 0x88,
    SERVER_TIME_QUERY: 0x89,
    SET_WORLD: 0x8B,
    LEAVE_WORLD: 0x8C,
    SET_POSITION: 0x8D,
    TOTAL_PLAYERS_DATA_QUERY: 0x91,
    SET_GAME_DATA: 0x92,
    GET_GAME_DATA: 0x93,
    SET_PLAYER_DATA: 0x94,
    DIRECT_SENDING: 0x95,

    GAMES_LIST_RESPONSE: 0xC1,
    TOP_LIST_RESPONSE: 0xC2,
    TOTAL_LIST_OF_PLAYERS_DATA: 0xCC,
    ATTACH_TO_GAME_RESPONSE: 0xC3,
    RESTORE_CONNECTION_RESPONSE: 0xC4,
    SERVER_TIME: 0xC6,
    SERVER_TIME_RESPONSE: 0xC7,
    SET_WORLD_RESPONSE: 0xC8,
    GAME_DATA_RESPONSE: 0xCD,
    DIRECT_RECEIVING: 0xCE,

    PLAYERS_NAME: 0xD5,
    PLAYERS_POSITION: 0xCF,
    PLAYERS_WORLD: 0xD1,
    PLAYERS_STATUS: 0xD2,
    PLAYERS_DATA: 0xD3,
    PLAYERS_RATING: 0xD4,

    zSERVER_VERSION_RESPONSE: 0xE1,
    zGAME_DATA_RESPONSE: 0xE2,
    zTIME_RESPONSE: 0xE3,
};

export enum GameType {
    UNCONFIGURED = -1,
    VAN_WAR = 0,
    MECHOSOMA = 1,
    PASSEMBLOSS = 2
}
